"""Central model catalog for Talking Pet backend routing and UI metadata."""

from __future__ import annotations

from copy import deepcopy

VIDEO_MODEL_ROUTES = {
    "fast": "wan-video/wan2.6-i2v-flash",
    "premium": "kwaivgi/kling-v2.6",
    "budget": "bytedance/seedance-1-pro-fast",
    "legacyFallback": "wan-video/wan-2.2-s2v",
}

SUPPORTED_MODELS = {
    "wan-video/wan2.6-i2v-flash": {
        "slug": "wan-video/wan2.6-i2v-flash",
        "name": "Wan 2.6 I2V Flash",
        "tier": "fast",
        "min_plan_tier": "creator",
        "quality_label": "fast",
        "blurb": "Fastest turnaround for short image-to-video generations.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": True,
            "generatesAudio": False,
            "maxDurationSeconds": 15,
        },
        "default_params": {},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
            "audio_url": "audio",
            "fps": "fps",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10, 15],
        "supported_fps": [24, 30],
        "tunable_params": [
            {
                "key": "fps",
                "label": "FPS",
                "type": "number",
                "min": 24,
                "max": 30,
                "step": 1,
                "default": 24,
                "help": "Higher FPS can improve smoothness but may cost more.",
            }
        ],
    },
    "wan-video/wan-2.6-i2v": {
        "slug": "wan-video/wan-2.6-i2v",
        "name": "Wan 2.6 I2V",
        "tier": "premium",
        "min_plan_tier": "creator",
        "quality_label": "balanced",
        "blurb": "Balanced quality and latency for most standard requests.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": True,
            "generatesAudio": False,
            "maxDurationSeconds": 15,
        },
        "default_params": {},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
            "audio_url": "audio",
            "fps": "fps",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10, 15],
        "supported_fps": [24, 30],
        "tunable_params": [
            {
                "key": "fps",
                "label": "FPS",
                "type": "number",
                "min": 24,
                "max": 30,
                "step": 1,
                "default": 24,
                "help": "Higher FPS can improve smoothness but may cost more.",
            }
        ],
    },
    "minimax/hailuo-2.3": {
        "slug": "minimax/hailuo-2.3",
        "name": "Hailuo 2.3",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "High-fidelity motion output with slower runtime than flash models.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"prompt_optimizer": False},
        "param_mapping": {
            "image_url": "first_frame_image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["512p", "768p", "1080p"],
        "supported_durations": [6, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "prompt_optimizer",
                "label": "Prompt optimizer",
                "type": "boolean",
                "default": False,
                "help": "May improve prompt adherence.",
            }
        ],
    },
    "minimax/hailuo-2.3-fast": {
        "slug": "minimax/hailuo-2.3-fast",
        "name": "Hailuo 2.3 Fast",
        "tier": "budget",
        "min_plan_tier": "creator",
        "quality_label": "cheap",
        "blurb": "Lower-cost Hailuo profile for quick iteration.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"prompt_optimizer": False},
        "param_mapping": {
            "image_url": "first_frame_image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["512p", "768p", "1080p"],
        "supported_durations": [6, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "prompt_optimizer",
                "label": "Prompt optimizer",
                "type": "boolean",
                "default": False,
                "help": "May improve prompt adherence.",
            }
        ],
    },
    "minimax/hailuo-02-fast": {
        "slug": "minimax/hailuo-02-fast",
        "name": "Hailuo 02 Fast",
        "tier": "budget",
        "min_plan_tier": "creator",
        "quality_label": "cheap",
        "blurb": "Cost-aware Hailuo 02 profile tuned for quick previews.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"prompt_optimizer": False, "go_fast": True},
        "param_mapping": {
            "image_url": "first_frame_image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["512p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "prompt_optimizer",
                "label": "Prompt optimizer",
                "type": "boolean",
                "default": False,
                "help": "May improve prompt adherence.",
            },
            {
                "key": "go_fast",
                "label": "Go fast",
                "type": "boolean",
                "default": True,
                "help": "Favors lower-latency generation behavior.",
            },
        ],
    },
    "kwaivgi/kling-v2.6": {
        "slug": "kwaivgi/kling-v2.6",
        "name": "Kling v2.6",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "Best premium visual fidelity for paid tiers.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": True,
            "maxDurationSeconds": 10,
        },
        "default_params": {"mode": "standard", "aspect_ratio": "1:1"},
        "param_mapping": {
            "image_url": "start_image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "aspect_ratio",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "mode",
                "label": "Mode",
                "type": "enum",
                "options": [
                    {"value": "standard", "label": "Standard"},
                    {"value": "pro", "label": "Pro"},
                ],
                "default": "standard",
                "help": "Pro mode can improve quality with longer runtime.",
            }
        ],
    },
    "kwaivgi/kling-v2.5-turbo-pro": {
        "slug": "kwaivgi/kling-v2.5-turbo-pro",
        "name": "Kling v2.5 Turbo Pro",
        "tier": "fast",
        "min_plan_tier": "studio",
        "quality_label": "balanced",
        "blurb": "Faster Kling profile when you want quality without full premium cost.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": True,
            "maxDurationSeconds": 10,
        },
        "default_params": {"mode": "standard", "aspect_ratio": "1:1"},
        "param_mapping": {
            "image_url": "start_image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "aspect_ratio",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "mode",
                "label": "Mode",
                "type": "enum",
                "options": [
                    {"value": "standard", "label": "Standard"},
                    {"value": "pro", "label": "Pro"},
                ],
                "default": "standard",
                "help": "Pro mode can improve quality with longer runtime.",
            }
        ],
    },
    "wan-video/wan-2.2-s2v": {
        "slug": "wan-video/wan-2.2-s2v",
        "name": "Wan v2.2 S2V",
        "tier": "legacy",
        "min_plan_tier": "creator",
        "quality_label": "balanced",
        "blurb": "Legacy speech-to-video path with native audio sync.",
        "requires_audio_input": True,
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": True,
            "generatesAudio": True,
            "maxDurationSeconds": 10,
        },
        "default_params": {"guidance_scale": 7.5, "num_inference_steps": 25},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
            "audio_url": "audio",
        },
        "supported_resolutions": ["768p", "1080p"],
        "supported_durations": [6, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "guidance_scale",
                "label": "Guidance",
                "type": "number",
                "min": 1,
                "max": 15,
                "step": 0.5,
                "default": 7.5,
                "help": "Higher values follow prompt text more strongly.",
            },
            {
                "key": "num_inference_steps",
                "label": "Steps",
                "type": "number",
                "min": 10,
                "max": 50,
                "step": 1,
                "default": 25,
                "help": "More steps can improve quality with added runtime.",
            },
        ],
    },
    "wan-video/wan-2.2-5b-fast": {
        "slug": "wan-video/wan-2.2-5b-fast",
        "name": "Wan 2.2 5B Fast",
        "tier": "budget",
        "min_plan_tier": "free",
        "quality_label": "cheap",
        "blurb": "Budget-friendly Wan 2.2 image-to-video with frame-based controls.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"frames_per_second": 16},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "num_frames",
            "resolution": "resolution",
            "fps": "frames_per_second",
        },
        "supported_resolutions": ["720p"],
        "supported_durations": [5, 10],
        "supported_fps": [16, 24],
        "frame_count_range": {"min": 81, "max": 121},
        "tunable_params": [
            {
                "key": "fps",
                "label": "FPS",
                "type": "number",
                "min": 16,
                "max": 24,
                "step": 8,
                "default": 16,
                "help": "Higher FPS increases motion smoothness and frame count.",
            }
        ],
    },
    "wan-video/wan-2.2-i2v-fast": {
        "slug": "wan-video/wan-2.2-i2v-fast",
        "name": "Wan 2.2 I2V Fast",
        "tier": "budget",
        "min_plan_tier": "free",
        "quality_label": "cheap",
        "blurb": "Fast Wan 2.2 I2V variant with practical frame-rate controls.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"frames_per_second": 16},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "num_frames",
            "resolution": "resolution",
            "fps": "frames_per_second",
        },
        "supported_resolutions": ["720p"],
        "supported_durations": [5, 10],
        "supported_fps": [16, 24],
        "frame_count_range": {"min": 81, "max": 121},
        "tunable_params": [
            {
                "key": "fps",
                "label": "FPS",
                "type": "number",
                "min": 16,
                "max": 24,
                "step": 8,
                "default": 16,
                "help": "Higher FPS increases motion smoothness and frame count.",
            }
        ],
    },
    "wan-video/wan-2.2-i2v-a14b": {
        "slug": "wan-video/wan-2.2-i2v-a14b",
        "name": "Wan 2.2 I2V A14B",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "Higher-cost Wan 2.2 profile for studio-grade motion quality.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"frames_per_second": 16},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "num_frames",
            "resolution": "resolution",
            "fps": "frames_per_second",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [16, 24],
        "frame_count_range": {"min": 81, "max": 121},
        "tunable_params": [
            {
                "key": "fps",
                "label": "FPS",
                "type": "number",
                "min": 16,
                "max": 24,
                "step": 8,
                "default": 16,
                "help": "Higher FPS increases motion smoothness and frame count.",
            }
        ],
    },
    "wan-video/wan-2.5-i2v": {
        "slug": "wan-video/wan-2.5-i2v",
        "name": "Wan 2.5 I2V",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "Premium Wan 2.5 image-to-video model with optional audio conditioning.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": True,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"enable_prompt_expansion": True},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
            "audio_url": "audio",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "enable_prompt_expansion",
                "label": "Prompt expansion",
                "type": "boolean",
                "default": True,
                "help": "Lets the model enrich short prompts before generation.",
            }
        ],
    },
    "wan-video/wan-2.5-i2v-fast": {
        "slug": "wan-video/wan-2.5-i2v-fast",
        "name": "Wan 2.5 I2V Fast",
        "tier": "fast",
        "min_plan_tier": "studio",
        "quality_label": "balanced",
        "blurb": "Lower-latency Wan 2.5 profile with optional audio conditioning.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": True,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"enable_prompt_expansion": True},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
            "audio_url": "audio",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "enable_prompt_expansion",
                "label": "Prompt expansion",
                "type": "boolean",
                "default": True,
                "help": "Lets the model enrich short prompts before generation.",
            }
        ],
    },
    "pixverse/pixverse-v4": {
        "slug": "pixverse/pixverse-v4",
        "name": "PixVerse v4",
        "tier": "premium",
        "min_plan_tier": "creator",
        "quality_label": "balanced",
        "blurb": "Creative PixVerse profile with motion/style controls.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 8,
        },
        "default_params": {"motion_mode": "normal", "sound_effect_switch": False},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "quality",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "motion_mode",
                "label": "Motion mode",
                "type": "enum",
                "options": [
                    {"value": "normal", "label": "Normal"},
                    {"value": "smooth", "label": "Smooth"},
                ],
                "default": "normal",
                "help": "Smooth can reduce jitter at additional generation cost.",
            },
            {
                "key": "sound_effect_switch",
                "label": "Generate sound effects",
                "type": "boolean",
                "default": False,
                "help": "Enable PixVerse sound effects generation.",
            },
        ],
    },
    "google/veo-3.1-fast": {
        "slug": "google/veo-3.1-fast",
        "name": "Google Veo 3.1 Fast",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "High-end Veo model for cinematic motion with optional native audio.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": True,
            "maxDurationSeconds": 10,
        },
        "default_params": {"generate_audio": False},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "generate_audio",
                "label": "Generate audio",
                "type": "boolean",
                "default": False,
                "help": "Enable only if you want Veo native audio in video output.",
            }
        ],
    },
    "kwaivgi/kling-v3-omni-video": {
        "slug": "kwaivgi/kling-v3-omni-video",
        "name": "Kling v3 Omni Video (Experimental)",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "Experimental catalog entry pending schema confirmation.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "runnable": False,
        "default_params": {},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [],
    },
    "veed/fabric-1.0": {
        "slug": "veed/fabric-1.0",
        "name": "VEED Fabric 1.0",
        "tier": "premium",
        "min_plan_tier": "studio",
        "quality_label": "quality",
        "blurb": "Audio-driven talking animation where clip length follows audio input.",
        "requires_audio_input": True,
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": True,
            "generatesAudio": False,
            "maxDurationSeconds": 15,
        },
        "default_params": {},
        "param_mapping": {
            "image_url": "image",
            "resolution": "resolution",
            "audio_url": "audio",
        },
        "supported_resolutions": ["720p", "1080p"],
        "supported_durations": [5, 10],
        "supported_fps": [],
        "tunable_params": [],
    },
    "bytedance/seedance-1-pro-fast": {
        "slug": "bytedance/seedance-1-pro-fast",
        "name": "SeeDance-1 Pro Fast",
        "tier": "budget",
        "min_plan_tier": "free",
        "quality_label": "cheap",
        "blurb": "Cost-efficient generations for budget-sensitive workloads.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"guidance_scale": 7.5, "num_inference_steps": 20},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["480p", "720p", "1080p"],
        "supported_durations": [6, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "guidance_scale",
                "label": "Guidance",
                "type": "number",
                "min": 1,
                "max": 15,
                "step": 0.5,
                "default": 7.5,
                "help": "Higher values follow prompt text more strongly.",
            },
            {
                "key": "num_inference_steps",
                "label": "Steps",
                "type": "number",
                "min": 10,
                "max": 50,
                "step": 1,
                "default": 20,
                "help": "More steps can improve quality with added runtime.",
            },
        ],
    },
    "bytedance/seedance-1-pro": {
        "slug": "bytedance/seedance-1-pro",
        "name": "SeeDance-1 Pro",
        "tier": "premium",
        "min_plan_tier": "creator",
        "quality_label": "quality",
        "blurb": "Higher-quality SeeDance profile at increased cost.",
        "capabilities": {
            "supportsImageToVideo": True,
            "supportsTextToVideo": False,
            "supportsAudioIn": False,
            "generatesAudio": False,
            "maxDurationSeconds": 10,
        },
        "default_params": {"guidance_scale": 7.5, "num_inference_steps": 25},
        "param_mapping": {
            "image_url": "image",
            "prompt": "prompt",
            "seconds": "duration",
            "resolution": "resolution",
        },
        "supported_resolutions": ["480p", "720p", "1080p"],
        "supported_durations": [6, 10],
        "supported_fps": [],
        "tunable_params": [
            {
                "key": "guidance_scale",
                "label": "Guidance",
                "type": "number",
                "min": 1,
                "max": 15,
                "step": 0.5,
                "default": 7.5,
                "help": "Higher values follow prompt text more strongly.",
            },
            {
                "key": "num_inference_steps",
                "label": "Steps",
                "type": "number",
                "min": 10,
                "max": 50,
                "step": 1,
                "default": 25,
                "help": "More steps can improve quality with added runtime.",
            },
        ],
    },
}

DEFAULT_MODEL = VIDEO_MODEL_ROUTES["fast"]
PROMPT_ONLY_FALLBACK_MODEL = DEFAULT_MODEL


def get_supported_models() -> dict:
    """Return a deep copy so callers can safely enrich metadata per request."""

    return deepcopy(SUPPORTED_MODELS)
