services:
  - type: web
    name: talking-pet-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ELEVEN_API_KEY
        sync: false
      - key: DID_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        value: "*"
