# ---- requirements.txt (create this file at repo root) ----
# Copy exactly these lines:
# fastapi web framework
fastapi
# ASGI server for FastAPI
uvicorn[standard]
# HTTP client for provider calls (ElevenLabs, D-ID, Supabase REST)
httpx
# Load env vars in local dev
python-dotenv

# ---- render.yaml (create this file at repo root) ----
# Paste into render.yaml and commit. Values are provided in Render dashboard, not here.
services:
  - type: web
    name: talking-pet-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: ELEVEN_API_KEY
        sync: false    # set the value in Render → Environment
      - key: DID_API_KEY
        sync: false    # set the value in Render → Environment (format: key:secret if D-ID provides both)
      - key: ALLOWED_ORIGIN
        value: "*"     # set to your frontend origin later
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: SUPABASE_BUCKET
        value: pets     # or your bucket name
